export const seoKeywords = [
  // Company Specific
  'XPHUB',
  'XP HUB',
  'XP Hub Logistics',
  'XP Hub Transportation',

  // Single Words
  'transportation',
  'trucking',
  'hauling',
  'delivery',
  'carrier',
  'transport',
  'tanker',
  'trailer',
  'bulk',
  'liquid',
  'cargo',
  'kosher',
  'foodgrade',
  'nationwide',
  'interstate',
  'domestic',
  'distribution',
  'supply',
  'reliable',
  'professional',
  'certified',
  'safe',
  'quality',
  'solutions',

  // Core Business Terms
  'logistics',
  'transportation',
  'shipping',
  'freight',
  'trucking',

  // Liquid Bulk Specific
  'liquid bulk transport',
  'tank truck',
  'tanker truck',
  'bulk liquid logistics',
  'liquid cargo',
  'liquid freight',
  'bulk liquid hauling',
  'liquid bulk carrier',
  'liquid bulk shipping',
  'liquid bulk transportation services',
  'bulk liquid delivery',
  'liquid bulk freight services',

  // Cargo Types
  'chemical transport',
  'food grade transport',
  'petroleum transport',
  'liquid food transport',
  'edible oils transport',
  'industrial liquids',
  'non-hazardous liquid transport',
  'food-safe liquid transport',
  'vegetable oil transport',
  'corn syrup transport',
  'glycerin transport',
  'food ingredients transport',
  'beverage ingredients transport',
  'liquid sweetener transport',

  // Industry Specific
  'DOT certified',
  'food grade certified',
  'bulk liquid solutions',
  'tank wash facilities',
  'kosher certified transport',
  'FDA compliant transport',
  'FSMA compliant',
  'food safety transport',
  'temperature controlled liquid transport',
  'food grade tank wash',
  'kosher approved transport',
  'food safety certified transport',

  // Service Areas
  'nationwide liquid transport',
  'US liquid bulk',
  'interstate liquid transport',
  'coast to coast liquid transport',
  'cross country liquid transport',
  'domestic liquid bulk transport',
  'US bulk liquid carrier',
  'American liquid bulk transport',

  // Equipment
  'tank trailer',
  'liquid bulk trailer',
  'ISO tank container',
  'stainless steel tanker',
  'food grade tanker',
  'sanitary tanker',
  'insulated tank trailer',
  'temperature controlled tanker',
  'food grade tank trailer',
  'stainless steel tank trailer',

  // Quality/Safety
  'safe liquid transport',
  'certified liquid carrier',
  'quality bulk transport',
  'food safety certified',
  'reliable liquid transport',
  'trusted bulk carrier',
  'professional tank truck service',
  'experienced liquid bulk carrier',
  'certified food grade transport',
  'quality assured transport',

  // Industry Solutions
  'bulk liquid shipping solutions',
  'food grade logistics solutions',
  'liquid bulk supply chain',
  'bulk liquid distribution',
  'food grade bulk transport solutions',
  'liquid ingredient logistics',
  'bulk liquid delivery service',
];
